import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/Context/CartContext";
import { AuthProvider } from "@/Context/AuthContext";
// import 'bootstrap/dist/css/bootstrap.min.css';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900" ]
});

export const metadata: Metadata = {
  title: "Semight Fashion Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
    <CartProvider>
      <html lang="en">
        <body className={poppins.className}>{children}</body>
      </html>
    </CartProvider>
    </AuthProvider>
  );
}
